# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
import os
from os.path import join, dirname
from dotenv import load_dotenv

dotenv_path = join(dirname(__file__), '.env')
load_dotenv(dotenv_path)

USER = os.environ.get("URL")
PASSWORD = os.environ.get("PASSWORD")

class TestDefaultSuite():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_abrirLenoxlogin(self):
    self.driver.find_element(By.ID, "Usuario").send_keys(USER)
    self.driver.find_element(By.ID, "Password").send_keys("lenox2021")
    self.driver.find_element(By.ID, "btnIngresar").click()
    self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(3) label").click()
    self.driver.find_element(By.LINK_TEXT, "Planificacion horaria").click()

