# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from locators import planificacion_horaria
import unittest
import os
from os.path import join, dirname
from dotenv import load_dotenv

dotenv_path = join(dirname(__file__), '.env')
load_dotenv(dotenv_path)

USER = os.environ.get("USER")
PASSWORD = os.environ.get("PASSWORD")
URL = os.environ.get("URL")

#locator = planificacion_horaria

#driver = webdriver.Chrome('./chromedriver.exe')
#driver.get(URL)
#driver.implicitly_wait(10)
  
class PlanificacionHoraria(unittest.TestCase):
  @classmethod
  def setup(self):
   self.driver = webdriver.Chrome('./chromedriver.exe')
   
  def init(self):
   driver = self.driver
   driver.get(URL)
   driver.implicitly_wait(30)
   driver.maximize_window()
  
  @classmethod
  def tearDown(self):
   self.driver.close()

if __name__ == "__main__":
  unittest.main()







  

